---
name: auto-merge
on:
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    if: github.triggering_actor == 'dependabot[bot]'
    name: Auto merge pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Approve Dependabot PR
      run: gh pr review --approve "${PR_URL}"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.MACHINE_TOKEN }}
    - if: contains(github.event.pull_request.labels.*.name, 'github_actions')
      name: Enable auto-merge for Dependabot PR
      run: gh pr merge --auto --merge "${PR_URL}"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
